fileExtension=js
defaultLayoutStrategyId=direct-file-system-homomorphism
emitLinkFiles=false
staticFiles=package.json,config.json
template.processor.declaration=processor.peb
template.node.declaration=processor.peb
template.group.declaration=composite.peb
template.composite.declaration=composite.peb
template.link.declaration=link-declaration.peb
template.link.instantiation=link-instantiation.peb
template.note.declaration=note.peb
template.child.import=child-import.peb
template.runtime.support=runtime.peb
template.composite.single-file=assembly-single.peb
template.composite.file-based=assembly-file.peb
template.static-file.path=static-path.peb
project.1.path={{ safeProjectName }}/package.json
project.1.content=package-json.peb
project.1.reason=Node.js package manifest

