package com.orchestra.compiler.generic

import com.orchestra.compiler.api.CompilationResult
import com.orchestra.compiler.api.CompilerOptions
import com.orchestra.compiler.api.CompilerPlugin
import com.orchestra.compiler.api.GeneratedElementKind
import com.orchestra.compiler.api.GeneratedFile
import com.orchestra.core.classification.LinkClassifier
import com.orchestra.core.classification.LinkStereotype
import com.orchestra.core.classification.NodeStereotype
import com.orchestra.core.classification.stereotype
import com.orchestra.core.diagnostics.Diagnostic
import com.orchestra.core.diagnostics.DiagnosticSeverity
import com.orchestra.core.model.InflowDocument
import com.orchestra.core.model.Node
import com.orchestra.core.model.NodeId
import com.orchestra.core.model.getElementById
import com.orchestra.core.model.getElementsByIds
import com.orchestra.core.model.effectiveLanguageId
import com.orchestra.core.model.effectiveTechnologyId
import com.orchestra.core.validation.DocumentValidator

fun compileWithMethodDispatch(
    compiler: CompilerPlugin,
    document: InflowDocument,
    options: CompilerOptions,
): CompilationResult {
    val diagnostics = compiler.validate(document).ifEmpty { DocumentValidator.validate(document) }.toMutableList()
    if (diagnostics.any { it.severity == DiagnosticSeverity.Error }) {
        return CompilationResult(null, diagnostics, success = false)
    }

    val scopeIds = methodCompileScopeIds(document, options.scopeNodeIds)
    val staticFileNames = compiler.getStaticFiles(document, options).toSet()
    val files = mutableListOf<GeneratedFile>()

    document.nodes.values
        .filter { it.id in scopeIds }
        .filterNot { it.isCompilerDefinition(document) }
        .sortedBy { it.id.value }
        .forEach { node ->
            if (!node.isLink && (node.stereotype(document) == NodeStereotype.StaticFile || node.name in staticFileNames)) {
                files += methodStaticFileFor(node)
                return@forEach
            }

            val text = runCatching { renderMethodTemplate(document, node, options, compiler.generatedDeclarationFor(document, node, options)).trim() }
                .onFailure { error ->
                    diagnostics += Diagnostic(
                        DiagnosticSeverity.Error,
                        "Compiler method failed for '${node.name}': ${error.message ?: error::class.simpleName}",
                        node.id,
                        sourcePluginId = compiler.id,
                    )
                }
                .getOrNull()
                ?: return@forEach
            if (text.isBlank()) return@forEach
            files += methodGeneratedFileFor(document, node, text)
        }

    if (diagnostics.any { it.severity == DiagnosticSeverity.Error }) {
        return CompilationResult(null, diagnostics, success = false)
    }

    return CompilationResult(
        generatedProject = compiler.layoutStrategy(options).layout(
            document,
            options.projectName ?: document.name,
            files.distinctBy { it.path },
            options,
        ),
        diagnostics = diagnostics,
        success = true,
    )
}

private fun methodGeneratedFileFor(document: InflowDocument, node: Node, content: String): GeneratedFile {
    val stereotype = methodStereotypeForContext(document, node)
    val kind = when {
        node.isLink -> GeneratedElementKind.Link
        node.children.isEmpty() -> GeneratedElementKind.TerminalEntity
        else -> GeneratedElementKind.CompositeEntity
    }
    return GeneratedFile(
        path = methodGeneratedPath(document, node, stereotype),
        content = content,
        originNodeId = node.id,
        reason = "Generated by ${stereotype.name} compiler method",
        elementKind = kind,
    )
}

private fun methodStaticFileFor(node: Node): GeneratedFile =
    GeneratedFile(
        path = node.metadata["path"]?.takeIf { it.isNotBlank() }
            ?: node.metadata["file"]?.takeIf { it.isNotBlank() }
            ?: node.name,
        content = node.text.declaration.ifBlank { node.text.specification },
        originNodeId = node.id,
        reason = "Literal static file encoded in the flow design",
        elementKind = GeneratedElementKind.StaticFile,
    )

private fun methodGeneratedPath(document: InflowDocument, node: Node, stereotype: NodeStereotype): String {
    node.metadata["path"]?.takeIf { it.isNotBlank() }?.let { return it }
    node.metadata["file"]?.takeIf { it.isNotBlank() }?.let { return it }
    val directory = when {
        node.isLink -> "links"
        stereotype in setOf(NodeStereotype.CompositeWorker, NodeStereotype.CompositeErrorHandler, NodeStereotype.TestSuite) -> "composites"
        stereotype == NodeStereotype.ServiceLibrary -> "libraries"
        else -> "nodes"
    }
    return "$directory/${methodSafeFileName(node.name)}.${methodExtensionFor(document, node)}"
}

private fun methodExtensionFor(document: InflowDocument, node: Node): String =
    node.technology.fileExtension.ifBlank {
        when (document.effectiveLanguageId(node.id)) {
            "markdown" -> "md"
            "kotlin" -> "kt"
            "javascript" -> "js"
            "typescript" -> "ts"
            "json" -> "json"
            else -> "txt"
        }
    }.trim().trimStart('.').ifBlank { "txt" }

private fun methodStereotypeForContext(document: InflowDocument, node: Node): NodeStereotype =
    if (!node.isLink) {
        node.stereotype(document)
    } else {
        when (LinkClassifier.classify(document, node)) {
            LinkStereotype.Transport -> NodeStereotype.Transport
            LinkStereotype.ErrorPipe -> NodeStereotype.ErrorPipe
            LinkStereotype.UsageImport,
            LinkStereotype.DependencyInjection -> NodeStereotype.DependencyInjection
        }
    }

private fun renderMethodTemplate(document: InflowDocument, node: Node, options: CompilerOptions, template: String): String {
    val link = node.link
    val values = linkedMapOf(
        "id" to node.id.value,
        "name" to node.name,
        "options.projectName" to (options.projectName ?: document.name),
        "node.id" to node.id.value,
        "node.name" to node.name,
        "node.kind.name" to node.kind.name,
        "node.kind.ordinal" to node.kind.ordinal.toString(),
        "node.kind" to node.kind.name,
        "node.parentId" to node.parentId?.value.orEmpty(),
        "node.stereotype" to methodStereotypeForContext(document, node).name,
        "node.children.size" to node.children.size.toString(),
        "node.incomingLinks" to node.incomingLinks.joinToString(",") { it.value },
        "node.outgoingLinks" to node.outgoingLinks.joinToString(",") { it.value },
        "node.isComposite" to node.children.isNotEmpty().toString(),
        "node.isLink" to node.isLink.toString(),
        "node.isTerminal" to node.children.isEmpty().toString(),
        "node.layout" to node.layout.toString(),
        "node.link.sourceNodeId" to link?.sourceNodeId?.value.orEmpty(),
        "node.link.targetNodeId" to link?.targetNodeId?.value.orEmpty(),
        "node.link.sourcePortName" to link?.sourcePortName.orEmpty(),
        "node.link.targetPortName" to link?.targetPortName.orEmpty(),
        "node.metadata.size" to node.metadata.size.toString(),
        "node.metadata" to node.metadata.entries.joinToString(",") { "${it.key}=${it.value}" },
        "node.pluginData" to node.pluginData.entries.joinToString(",") { "${it.key}=${it.value}" },
        "node.ports" to node.ports.joinToString(",") { it.name },
        "node.text.instantiationLanguageId" to node.text.instantiationLanguageId,
        "node.text.instantiation" to node.text.instantiation,
        "node.text.declarationLanguageId" to node.text.declarationLanguageId,
        "node.text.declaration" to node.text.declaration,
        "node.text.specificationLanguageId" to node.text.specificationLanguageId,
        "node.text.specification" to node.text.specification,
        "node.text.aiInstructionsLanguageId" to node.text.aiInstructionsLanguageId,
        "node.text.aiInstructions" to node.text.aiInstructions,
        "node.text.testsLanguageId" to node.text.testsLanguageId,
        "node.text.tests" to node.text.tests,
        "stereotype" to methodStereotypeForContext(document, node).name,
        "language" to document.effectiveLanguageId(node.id),
        "technology" to document.effectiveTechnologyId(node.id),
        "technology.languageId" to document.effectiveLanguageId(node.id),
        "technology.technologyId" to document.effectiveTechnologyId(node.id),
        "technology.compilerId" to node.technology.compilerId,
        "technology.fileExtension" to node.technology.fileExtension,
        "declaration" to node.text.declaration,
        "instantiation" to node.text.instantiation,
        "specification" to node.text.specification,
        "tests" to node.text.tests,
        "usageInstructions" to node.text.aiInstructions,
        "text.declaration" to node.text.declaration,
        "text.instantiation" to node.text.instantiation,
        "text.specification" to node.text.specification,
        "text.tests" to node.text.tests,
        "text.usageInstructions" to node.text.aiInstructions,
        "children" to document.getElementsByIds(node.children).values.joinToString(",") { it.name },
        "incomingLinks" to document.getElementsByIds(node.incomingLinks).values.joinToString(",") { it.name },
        "outgoingLinks" to document.getElementsByIds(node.outgoingLinks).values.joinToString(",") { it.name },
        "ports" to node.ports.joinToString(",") { it.name },
    )
    if (link != null) {
        values += mapOf(
            "link.sourceNodeId" to link.sourceNodeId.value,
            "link.targetNodeId" to link.targetNodeId.value,
            "link.sourcePortName" to link.sourcePortName,
            "link.targetPortName" to link.targetPortName,
            "link.transportKind" to link.transportKind,
            "link.variableName" to node.name,
            "link.typeName" to link.typeName,
            "link.typeDefinition" to link.payloadDefinition,
            "link.payloadDefinition" to link.payloadDefinition,
            "sourceNode.name" to document.getElementById(link.sourceNodeId)?.name.orEmpty(),
            "targetNode.name" to document.getElementById(link.targetNodeId)?.name.orEmpty(),
        )
    }
    var rendered = template
    values.forEach { (key, value) ->
        rendered = rendered.replace("\${$key}", value)
        rendered = rendered.replace("{{$key}}", value)
    }
    return rendered
}

private fun Node.isCompilerDefinition(document: InflowDocument): Boolean =
    name.equals("@Compiler", ignoreCase = true) ||
        stereotype(document) == NodeStereotype.CompilerTemplate ||
        name.trim().equals("@StaticFile", ignoreCase = true)

private fun methodCompileScopeIds(document: InflowDocument, requested: Set<NodeId>): Set<NodeId> {
    if (requested.isEmpty()) return document.nodes.keys
    val result = linkedSetOf<NodeId>()
    fun include(id: NodeId) {
        val node = document.nodes[id] ?: return
        if (result.add(id) && !node.isLink) node.children.forEach(::include)
    }
    requested.forEach(::include)
    return result
}

private fun methodSafeFileName(value: String): String =
    value.lowercase()
        .replace(Regex("[^a-z0-9_.-]+"), "_")
        .trim('_')
        .ifBlank { "generated" }
